#!/usr/bin/env bash
# Configures nginx with a custom 404 error page containing a specific string
apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
